// Deutsche Ländernamen zu den ISO-3-Codes des Datensatzes (erzeugt mit pycountry).
const LAENDERNAMEN = {
  "ABW": "Aruba",
  "AGO": "Angola",
  "AIA": "Anguilla",
  "ALB": "Albanien",
  "AND": "Andorra",
  "ARE": "Vereinigte Arabische Emirate",
  "ARG": "Argentinien",
  "ARM": "Armenien",
  "ASM": "Amerikanisch-Samoa",
  "ATA": "Antarktis",
  "ATF": "Französische Süd- und Antarktisgebiete",
  "AUS": "Australien",
  "AUT": "Österreich",
  "AZE": "Aserbaidschan",
  "BDI": "Burundi",
  "BEL": "Belgien",
  "BEN": "Benin",
  "BFA": "Burkina Faso",
  "BGD": "Bangladesch",
  "BGR": "Bulgarien",
  "BHR": "Bahrain",
  "BHS": "Bahamas",
  "BIH": "Bosnien und Herzegowina",
  "BLR": "Belarus",
  "BOL": "Bolivien",
  "BRA": "Brasilien",
  "BRB": "Barbados",
  "BWA": "Botsuana",
  "CAF": "Zentralafrikanische Republik",
  "CHE": "Schweiz",
  "CHL": "Chile",
  "CHN": "China",
  "CIV": "Elfenbeinküste",
  "CMR": "Kamerun",
  "CN": "China",
  "COL": "Kolumbien",
  "COM": "Komoren",
  "CPV": "Kap Verde",
  "CRI": "Costa Rica",
  "CUB": "Kuba",
  "CYM": "Cayman-Inseln",
  "CYP": "Zypern",
  "CZE": "Tschechien",
  "DEU": "Deutschland",
  "DJI": "Dschibuti",
  "DMA": "Dominica",
  "DNK": "Dänemark",
  "DOM": "Dominikanische Republik",
  "DZA": "Algerien",
  "ECU": "Ecuador",
  "EGY": "Ägypten",
  "ESP": "Spanien",
  "EST": "Estland",
  "ETH": "Äthiopien",
  "FIN": "Finnland",
  "FJI": "Fidschi",
  "FRA": "Frankreich",
  "FRO": "Färöer-Inseln",
  "GAB": "Gabun",
  "GBR": "Großbritannien",
  "GEO": "Georgien",
  "GGY": "Guernsey",
  "GHA": "Ghana",
  "GIB": "Gibraltar",
  "GLP": "Guadeloupe",
  "GNB": "Guinea-Bissau",
  "GRC": "Griechenland",
  "GTM": "Guatemala",
  "GUY": "Guyana",
  "HKG": "Hongkong",
  "HND": "Honduras",
  "HRV": "Kroatien",
  "HUN": "Ungarn",
  "IDN": "Indonesien",
  "IMN": "Insel Man",
  "IND": "Indien",
  "IRL": "Irland",
  "IRN": "Iran",
  "IRQ": "Irak",
  "ISL": "Island",
  "ISR": "Israel",
  "ITA": "Italien",
  "JAM": "Jamaika",
  "JEY": "Jersey",
  "JOR": "Jordanien",
  "JPN": "Japan",
  "KAZ": "Kasachstan",
  "KEN": "Kenia",
  "KHM": "Kambodscha",
  "KIR": "Kiribati",
  "KNA": "St. Kitts und Nevis",
  "KOR": "Südkorea",
  "KWT": "Kuwait",
  "LAO": "Laos",
  "LBN": "Libanon",
  "LBY": "Libyen",
  "LCA": "St. Lucia",
  "LIE": "Liechtenstein",
  "LKA": "Sri Lanka",
  "LTU": "Litauen",
  "LUX": "Luxemburg",
  "LVA": "Lettland",
  "MAC": "Macao",
  "MAR": "Marokko",
  "MCO": "Monaco",
  "MDG": "Madagaskar",
  "MDV": "Malediven",
  "MEX": "Mexiko",
  "MKD": "Nordmazedonien",
  "MLI": "Mali",
  "MLT": "Malta",
  "MMR": "Myanmar",
  "MNE": "Montenegro",
  "MOZ": "Mosambik",
  "MRT": "Mauretanien",
  "MUS": "Mauritius",
  "MWI": "Malawi",
  "MYS": "Malaysia",
  "MYT": "Mayotte",
  "NAM": "Namibia",
  "NCL": "Neukaledonien",
  "NGA": "Nigeria",
  "NIC": "Nicaragua",
  "NLD": "Niederlande",
  "NOR": "Norwegen",
  "NPL": "Nepal",
  "NZL": "Neuseeland",
  "OMN": "Oman",
  "PAK": "Pakistan",
  "PAN": "Panama",
  "PER": "Peru",
  "PHL": "Philippinen",
  "PLW": "Palau",
  "POL": "Polen",
  "PRI": "Puerto Rico",
  "PRT": "Portugal",
  "PRY": "Paraguay",
  "PYF": "Französisch-Polynesien",
  "QAT": "Katar",
  "ROU": "Rumänien",
  "RUS": "Russland",
  "RWA": "Ruanda",
  "SAU": "Saudi-Arabien",
  "SDN": "Sudan",
  "SEN": "Senegal",
  "SGP": "Singapur",
  "SLE": "Sierra Leone",
  "SLV": "El Salvador",
  "SMR": "San Marino",
  "SRB": "Serbien",
  "STP": "São Tomé und Príncipe",
  "SUR": "Suriname",
  "SVK": "Slowakei",
  "SVN": "Slowenien",
  "SWE": "Schweden",
  "SYC": "Seychellen",
  "SYR": "Syrien",
  "TGO": "Togo",
  "THA": "Thailand",
  "TJK": "Tadschikistan",
  "TMP": "Osttimor",
  "TUN": "Tunesien",
  "TUR": "Türkei",
  "TWN": "Taiwan",
  "TZA": "Tansania",
  "UGA": "Uganda",
  "UKR": "Ukraine",
  "UMI": "United States Minor Outlying Islands",
  "UNK": "unbekannt",
  "URY": "Uruguay",
  "USA": "USA",
  "UZB": "Usbekistan",
  "VEN": "Venezuela",
  "VGB": "Britische Jungferninseln",
  "VNM": "Vietnam",
  "ZAF": "Südafrika",
  "ZMB": "Sambia",
  "ZWE": "Simbabwe"
  };
