table FACT_BOOKINGS
	lineageTag: 6c1b786b-0f4d-5443-bd18-8c35336f7684

	measure 'Anzahl Buchungen' = COUNTROWS(FACT_BOOKINGS)
		formatString: #,0
		lineageTag: 893207ed-2314-5a1c-9a62-931f916a77bc

	measure 'Stornoquote %' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_BOOKINGS), FACT_BOOKINGS[is_canceled] = 1),
			    COUNTROWS(FACT_BOOKINGS))
		formatString: 0.0 %
		lineageTag: 4a84c9b7-51f2-586d-bfed-238c5d35f1a7

	measure 'Ø Vorlaufzeit' = AVERAGE(FACT_BOOKINGS[lead_time])
		formatString: #,0.0
		lineageTag: 5ef7013c-c8f2-5de8-a92e-c469648aaafb

	measure 'Ø Aufenthaltsdauer' = AVERAGE(FACT_BOOKINGS[total_nights])
		formatString: #,0.00
		lineageTag: d92b69c9-9e9a-5c33-9065-e59c1d943720

	measure 'Gebuchte Zimmernächte' = SUM(FACT_BOOKINGS[total_nights])
		formatString: #,0
		lineageTag: ce150907-701c-57d6-a4d9-01656bb5026e

	measure 'Ø ADR' = AVERAGE(FACT_BOOKINGS[adr])
		formatString: #,0.00
		lineageTag: fd00c9b3-8c8b-5988-bd1b-78d9d04cb6ea

	measure 'Gebuchter Umsatz' = SUM(FACT_BOOKINGS[revenue])
		formatString: #,0
		lineageTag: ca97abb8-75ed-545c-b36f-468eb4174612

	measure 'Durch Stornierung entgangener Umsatz' = CALCULATE(SUM(FACT_BOOKINGS[revenue]), FACT_BOOKINGS[is_canceled] = 1)
		formatString: #,0
		lineageTag: 8648bcd0-6e9f-56e1-89b4-580f780f35d5

	measure Umsatz = CALCULATE(SUM(FACT_BOOKINGS[revenue]), FACT_BOOKINGS[is_canceled] = 0)
		formatString: #,0
		lineageTag: 3ae15481-f575-5bdf-8faf-a0e2a4754bb9

	measure 'Wiederholungsgast-Anteil %' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_BOOKINGS), FACT_BOOKINGS[is_repeated_guest] = 1),
			    COUNTROWS(FACT_BOOKINGS))
		formatString: 0.0 %
		lineageTag: b60ec9f6-b937-55d4-9ab4-acfe2d712ec2

	measure 'Anteil mit Sonderwünschen %' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_BOOKINGS), FACT_BOOKINGS[total_of_special_requests] > 0),
			    COUNTROWS(FACT_BOOKINGS))
		formatString: 0.0 %
		lineageTag: 052e1f92-86c0-5662-9f92-ca2e3f649b25

	measure 'Gebuchter Umsatz nach Stornodatum' =
			CALCULATE(
			    SUM(FACT_BOOKINGS[revenue]),
			    USERELATIONSHIP(FACT_BOOKINGS[reservation_status_date_key], DIM_DATE[date_key]))
		formatString: #,0
		lineageTag: de480ac9-d416-512a-9959-65295e2740f5

	measure 'Ø gebuchter Umsatz je Buchung' = DIVIDE([Gebuchter Umsatz], [Anzahl Buchungen])
		formatString: #,0.00
		lineageTag: d1e8be93-7dde-5d84-86e2-28988eed1543

	column booking_id
		dataType: int64
		formatString: 0
		lineageTag: c8a0be68-3f4d-53fe-ada8-f8ae1e9a4a66
		summarizeBy: none
		sourceColumn: booking_id

		annotation SummarizationSetBy = User

	column hotel_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0f495f0b-a4fb-59b9-870f-835e17374a1f
		summarizeBy: none
		sourceColumn: hotel_id

		annotation SummarizationSetBy = User

	column arrival_date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee75ce7a-1eb3-52f8-901b-8c74bf8c2fa7
		summarizeBy: none
		sourceColumn: arrival_date_key

		annotation SummarizationSetBy = User

	column reservation_status_date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2e9ad294-d081-5d3e-b9bc-bbec11ce897b
		summarizeBy: none
		sourceColumn: reservation_status_date_key

		annotation SummarizationSetBy = User

	column market_segment_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aa4451d2-33e3-5d3e-87ab-7ebf8d51657d
		summarizeBy: none
		sourceColumn: market_segment_id

		annotation SummarizationSetBy = User

	column distribution_channel_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 36bbf7da-4713-5fdc-b071-de11ce4308a0
		summarizeBy: none
		sourceColumn: distribution_channel_id

		annotation SummarizationSetBy = User

	column customer_type_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b8d8f289-0cb3-5c7f-80b9-2febecfa72e9
		summarizeBy: none
		sourceColumn: customer_type_id

		annotation SummarizationSetBy = User

	column meal_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0db363b8-0ac0-5012-a065-004a0004a3a7
		summarizeBy: none
		sourceColumn: meal_id

		annotation SummarizationSetBy = User

	column deposit_type_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5c9fc45e-1193-5375-8a14-891162835e60
		summarizeBy: none
		sourceColumn: deposit_type_id

		annotation SummarizationSetBy = User

	column country_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 23fe0eee-1ec1-533e-947c-4f5465e71db5
		summarizeBy: none
		sourceColumn: country_id

		annotation SummarizationSetBy = User

	column is_canceled
		dataType: int64
		formatString: 0
		lineageTag: bd64ecd0-b736-5676-a364-2041b43a8997
		summarizeBy: none
		sourceColumn: is_canceled

		annotation SummarizationSetBy = User

	column lead_time
		dataType: int64
		formatString: 0
		lineageTag: aa882025-40ab-5f88-b8e8-add441049e38
		summarizeBy: none
		sourceColumn: lead_time

		annotation SummarizationSetBy = User

	column stays_in_weekend_nights
		dataType: int64
		formatString: 0
		lineageTag: 83099bdb-424b-5e03-b456-fe984aa0d05e
		summarizeBy: none
		sourceColumn: stays_in_weekend_nights

		annotation SummarizationSetBy = User

	column stays_in_week_nights
		dataType: int64
		formatString: 0
		lineageTag: 2504574c-bd12-522a-a3c3-e5c8a13dfd6d
		summarizeBy: none
		sourceColumn: stays_in_week_nights

		annotation SummarizationSetBy = User

	column total_nights
		dataType: int64
		formatString: 0
		lineageTag: d91d6a89-2ddd-5264-9af3-64dd222d4481
		summarizeBy: none
		sourceColumn: total_nights

		annotation SummarizationSetBy = User

	column adults
		dataType: int64
		formatString: 0
		lineageTag: b4d30208-7cba-5a43-9a93-40316f47feda
		summarizeBy: none
		sourceColumn: adults

		annotation SummarizationSetBy = User

	column children
		dataType: double
		formatString: 0.0
		lineageTag: 558e495a-3791-59b4-b10d-a27923c25537
		summarizeBy: none
		sourceColumn: children

		annotation SummarizationSetBy = User

	column babies
		dataType: int64
		formatString: 0
		lineageTag: 61896cf8-d934-5d78-886f-eb300e9ad786
		summarizeBy: none
		sourceColumn: babies

		annotation SummarizationSetBy = User

	column total_guests
		dataType: double
		formatString: 0.0
		lineageTag: f3befd67-0d8e-52bb-99c6-48cfbf484c79
		summarizeBy: none
		sourceColumn: total_guests

		annotation SummarizationSetBy = User

	column is_repeated_guest
		dataType: int64
		formatString: 0
		lineageTag: 253e171f-d7a3-50df-8124-a54e7ccf5407
		summarizeBy: none
		sourceColumn: is_repeated_guest

		annotation SummarizationSetBy = User

	column previous_cancellations
		dataType: int64
		formatString: 0
		lineageTag: 72977504-ad85-540a-a6a4-8392495c01d7
		summarizeBy: none
		sourceColumn: previous_cancellations

		annotation SummarizationSetBy = User

	column previous_bookings_not_canceled
		dataType: int64
		formatString: 0
		lineageTag: 1a18feb9-485e-5acc-bf3a-27761abb82e6
		summarizeBy: none
		sourceColumn: previous_bookings_not_canceled

		annotation SummarizationSetBy = User

	column reserved_room_type
		dataType: string
		lineageTag: 7e39ea05-9cca-5a6e-a507-55ccea5ff116
		summarizeBy: none
		sourceColumn: reserved_room_type

		annotation SummarizationSetBy = User

	column assigned_room_type
		dataType: string
		lineageTag: 3d90243d-8415-5e8b-b1c7-26151bafbadf
		summarizeBy: none
		sourceColumn: assigned_room_type

		annotation SummarizationSetBy = User

	column booking_changes
		dataType: int64
		formatString: 0
		lineageTag: 9a4c63eb-f5eb-59fa-a9e3-5324d4761776
		summarizeBy: none
		sourceColumn: booking_changes

		annotation SummarizationSetBy = User

	column days_in_waiting_list
		dataType: int64
		formatString: 0
		lineageTag: ab0e09ad-ada5-59c9-b051-0748eee6350f
		summarizeBy: none
		sourceColumn: days_in_waiting_list

		annotation SummarizationSetBy = User

	column adr
		dataType: double
		formatString: #,0.00
		lineageTag: 7ab7ac27-a6d4-59db-9d56-124c2f9e4341
		summarizeBy: none
		sourceColumn: adr

		annotation SummarizationSetBy = User

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 6591d06c-1969-5a01-8f46-e9467af5c094
		summarizeBy: none
		sourceColumn: revenue

		annotation SummarizationSetBy = User

	column required_car_parking_spaces
		dataType: int64
		formatString: 0
		lineageTag: 314b5cd9-ce97-5831-9677-1be635f3ed0c
		summarizeBy: none
		sourceColumn: required_car_parking_spaces

		annotation SummarizationSetBy = User

	column total_of_special_requests
		dataType: int64
		formatString: 0
		lineageTag: 95593c02-2645-5454-8498-090f2d50fbbb
		summarizeBy: none
		sourceColumn: total_of_special_requests

		annotation SummarizationSetBy = User

	column reservation_status
		dataType: string
		lineageTag: e81cc3ff-6de1-5f29-8591-1ab1dc8131cb
		summarizeBy: none
		sourceColumn: reservation_status

		annotation SummarizationSetBy = User

	column Lead-Time-Bucket =
			SWITCH(TRUE(),
			    FACT_BOOKINGS[lead_time] <= 7, "0-7",
			    FACT_BOOKINGS[lead_time] <= 30, "8-30",
			    FACT_BOOKINGS[lead_time] <= 90, "31-90",
			    "90+")
		dataType: string
		lineageTag: b49af994-78fc-51ff-93a3-f1b0e94a7ad5
		summarizeBy: none
		sortByColumn: Lead-Time-Sortierung

		annotation SummarizationSetBy = User

	column Lead-Time-Sortierung =
			SWITCH(TRUE(),
			    FACT_BOOKINGS[lead_time] <= 7, 1,
			    FACT_BOOKINGS[lead_time] <= 30, 2,
			    FACT_BOOKINGS[lead_time] <= 90, 3,
			    4)
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 20b7107d-d08c-54ff-865f-8a129e4e95cb
		summarizeBy: none

		annotation SummarizationSetBy = User

	partition FACT_BOOKINGS = m
		mode: import
		source =
				let
				    Quelle = PostgreSQL.Database("supabase.butscher.cloud:5433", "hotel"),
				    Tabelle = Quelle{[Schema="hotel_bi",Item="fact_bookings"]}[Data],
				    Typen = Table.TransformColumnTypes(Tabelle, {{"is_canceled", Int64.Type}, {"is_repeated_guest", Int64.Type}})
				in
				    Typen

	annotation PBI_ResultType = Table

