table FACT_BOOKINGS
	lineageTag: 6c1b786b-0f4d-5443-bd18-8c35336f7684

	measure 'Anzahl Buchungen' = COUNTROWS(FACT_BOOKINGS)
		formatString: #,0
		lineageTag: 893207ed-2314-5a1c-9a62-931f916a77bc

	measure 'Stornoquote %' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_BOOKINGS), FACT_BOOKINGS[is_canceled] = 1),
			    COUNTROWS(FACT_BOOKINGS))
		formatString: 0.0 %
		lineageTag: 4a84c9b7-51f2-586d-bfed-238c5d35f1a7

	measure 'Ø Vorlaufzeit' = AVERAGE(FACT_BOOKINGS[lead_time])
		formatString: #,0.0
		lineageTag: 5ef7013c-c8f2-5de8-a92e-c469648aaafb

	measure 'Ø Aufenthaltsdauer' = AVERAGE(FACT_BOOKINGS[total_nights])
		formatString: #,0.00
		lineageTag: d92b69c9-9e9a-5c33-9065-e59c1d943720

	measure 'Gebuchte Zimmernächte' = SUM(FACT_BOOKINGS[total_nights])
		formatString: #,0
		lineageTag: ce150907-701c-57d6-a4d9-01656bb5026e

	measure 'Ø ADR' = AVERAGE(FACT_BOOKINGS[adr])
		formatString: #,0.00
		lineageTag: fd00c9b3-8c8b-5988-bd1b-78d9d04cb6ea

	measure 'Gebuchter Umsatz' = SUM(FACT_BOOKINGS[revenue])
		formatString: #,0
		lineageTag: ca97abb8-75ed-545c-b36f-468eb4174612

	measure 'Durch Stornierung entgangener Umsatz' = CALCULATE(SUM(FACT_BOOKINGS[revenue]), FACT_BOOKINGS[is_canceled] = 1)
		formatString: #,0
		lineageTag: 8648bcd0-6e9f-56e1-89b4-580f780f35d5

	measure Umsatz = CALCULATE(SUM(FACT_BOOKINGS[revenue]), FACT_BOOKINGS[is_canceled] = 0)
		formatString: #,0
		lineageTag: 3ae15481-f575-5bdf-8faf-a0e2a4754bb9

	measure 'Wiederholungsgast-Anteil %' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_BOOKINGS), FACT_BOOKINGS[is_repeated_guest] = 1),
			    COUNTROWS(FACT_BOOKINGS))
		formatString: 0.0 %
		lineageTag: b60ec9f6-b937-55d4-9ab4-acfe2d712ec2

	measure 'Anteil mit Sonderwünschen %' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_BOOKINGS), FACT_BOOKINGS[total_of_special_requests] > 0),
			    COUNTROWS(FACT_BOOKINGS))
		formatString: 0.0 %
		lineageTag: 052e1f92-86c0-5662-9f92-ca2e3f649b25

	measure 'Gebuchter Umsatz nach Stornodatum' =
			CALCULATE(
			    SUM(FACT_BOOKINGS[revenue]),
			    USERELATIONSHIP(FACT_BOOKINGS[reservation_status_date_key], DIM_DATE[date_key]))
		formatString: #,0
		lineageTag: de480ac9-d416-512a-9959-65295e2740f5

	measure 'Ø gebuchter Umsatz je Buchung' = DIVIDE([Gebuchter Umsatz], [Anzahl Buchungen])
		formatString: #,0.00
		lineageTag: d1e8be93-7dde-5d84-86e2-28988eed1543

	measure Bezugsjahr = IF(ISFILTERED(DIM_DATE[year]), MAX(DIM_DATE[year]), 2016)
		formatString: 0
		lineageTag: 783e1ef0-effa-4edf-aadd-65b174143595

	measure Vergleichszeitraum =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			VAR mn = MINX(m, DIM_DATE[month])
			VAR mx = MAXX(m, DIM_DATE[month])
			RETURN IF(ISEMPTY(m), BLANK(),
			    IF(mn = mx, FORMAT(DATE(2000, mn, 1), "MMM"), FORMAT(DATE(2000, mn, 1), "MMM") & "–" & FORMAT(DATE(2000, mx, 1), "MMM"))
			    & " " & FORMAT(j - 1, "0"))
		lineageTag: 21dff206-c6a4-4e29-86cb-5b67185fb0f5

	measure 'Umsatz Bezugsjahr' =
			VAR j = [Bezugsjahr]
			RETURN CALCULATE([Umsatz], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
		formatString: #,0
		lineageTag: 5c4a5126-5449-4757-9582-8028e26363cb

	measure 'Umsatz Vergleich Bezugsjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Umsatz], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j, m)
		formatString: #,0
		lineageTag: 200aebd4-621f-4dee-856c-0ad52d78af74

	measure 'Umsatz Vergleich Vorjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Umsatz], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1, m)
		formatString: #,0
		lineageTag: 3e4c644a-82c9-47a3-87f2-d3dc54258281

	measure 'Umsatz Veränderung' =
			VAR a = [Umsatz Vergleich Bezugsjahr]
			VAR v = [Umsatz Vergleich Vorjahr]
			VAR d = DIVIDE(a - v, v)
			RETURN IF(ISBLANK(v), "kein Vorjahr im Datensatz",
			    IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zu " & [Vergleichszeitraum])
		lineageTag: fc3c603c-874c-4108-8f96-e9d6a456296d

	measure 'Umsatz Farbe' = IF(ISBLANK([Umsatz Vergleich Vorjahr]) || [Umsatz Vergleich Bezugsjahr] >= [Umsatz Vergleich Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: f712ff4c-b48d-4d67-a2ef-bc85171a8bb0

	measure 'Umsatz Titel' = "UMSATZ " & FORMAT([Bezugsjahr], "0")
		lineageTag: db5abc8c-6b1c-40ff-aa63-f3bf3fa943ba

	measure 'Umsatz Aktuell' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y = j, CALCULATE([Umsatz], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: #,0
		lineageTag: d49a832b-0636-4ed7-ac31-0de819e20d58

	measure 'Umsatz Vorjahre' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y <> j, CALCULATE([Umsatz], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: #,0
		lineageTag: 02ba376b-14ad-4e9d-9490-beb46be71cf3

	measure 'Buchungen Bezugsjahr' =
			VAR j = [Bezugsjahr]
			RETURN CALCULATE([Anzahl Buchungen], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
		formatString: #,0
		lineageTag: 93ec09e6-b41a-46f7-b9c1-8d8ce6110a59

	measure 'Buchungen Vergleich Bezugsjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Anzahl Buchungen], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j, m)
		formatString: #,0
		lineageTag: 2f058303-9198-4adb-ad8b-3decdadf6012

	measure 'Buchungen Vergleich Vorjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Anzahl Buchungen], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1, m)
		formatString: #,0
		lineageTag: 5fc160a1-5008-44d9-ba7c-4c401e68a48f

	measure 'Buchungen Veränderung' =
			VAR a = [Buchungen Vergleich Bezugsjahr]
			VAR v = [Buchungen Vergleich Vorjahr]
			VAR d = DIVIDE(a - v, v)
			RETURN IF(ISBLANK(v), "kein Vorjahr im Datensatz",
			    IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zu " & [Vergleichszeitraum])
		lineageTag: 3ed0eb38-d2fc-432c-8959-ee91eb8e2678

	measure 'Buchungen Farbe' = IF(ISBLANK([Buchungen Vergleich Vorjahr]) || [Buchungen Vergleich Bezugsjahr] >= [Buchungen Vergleich Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: a1dbd239-1679-4443-a4a2-878257231694

	measure 'Buchungen Titel' = "BUCHUNGEN " & FORMAT([Bezugsjahr], "0")
		lineageTag: e9f7a1e7-84a0-4909-97c9-ccb0a12646fd

	measure 'Buchungen Aktuell' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y = j, CALCULATE([Anzahl Buchungen], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: #,0
		lineageTag: 86859cf3-62f7-48ec-9c34-d995088fbc70

	measure 'Buchungen Vorjahre' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y <> j, CALCULATE([Anzahl Buchungen], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: #,0
		lineageTag: ddc0169f-79c9-4ed5-93fe-913380a290a2

	measure 'Stornoquote Bezugsjahr' =
			VAR j = [Bezugsjahr]
			RETURN CALCULATE([Stornoquote %], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
		formatString: 0.0 %
		lineageTag: c809c96c-d562-4b43-bb6f-f5d264a0c2f9

	measure 'Stornoquote Vergleich Bezugsjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Stornoquote %], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j, m)
		formatString: 0.0 %
		lineageTag: 6ae3684b-9cd8-4020-a3d4-08018a100343

	measure 'Stornoquote Vergleich Vorjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Stornoquote %], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1, m)
		formatString: 0.0 %
		lineageTag: c15c85cf-d692-45f3-8f43-2271455a6ba8

	measure 'Stornoquote Veränderung' =
			VAR a = [Stornoquote Vergleich Bezugsjahr]
			VAR v = [Stornoquote Vergleich Vorjahr]
			VAR d = (a - v) * 100
			RETURN IF(ISBLANK(v), "kein Vorjahr im Datensatz",
			    IF(d > 0, "+", IF(d < 0, "−", "±")) & FORMAT(ABS(d), "0.0") & " Punkte zu " & [Vergleichszeitraum])
		lineageTag: ed653260-826f-4b02-b70a-2ee10dccbfca

	measure 'Stornoquote Farbe' = IF(ISBLANK([Stornoquote Vergleich Vorjahr]) || [Stornoquote Vergleich Bezugsjahr] <= [Stornoquote Vergleich Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: f820470c-49c0-4029-92e4-ac66d9b7ec6a

	measure 'Stornoquote Titel' = "STORNOQUOTE " & FORMAT([Bezugsjahr], "0")
		lineageTag: 6a515183-4849-4554-8ec8-83429f286612

	measure 'Stornoquote Aktuell' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y = j, CALCULATE([Stornoquote %], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: 0.0 %
		lineageTag: cc2cc113-47d4-4a74-b294-8f14012789aa

	measure 'Stornoquote Vorjahre' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y <> j, CALCULATE([Stornoquote %], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: 0.0 %
		lineageTag: bdcf7181-e303-41ac-9afb-80df5ecc63bc

	measure 'ADR Bezugsjahr' =
			VAR j = [Bezugsjahr]
			RETURN CALCULATE([Ø ADR], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
		formatString: #,0.00
		lineageTag: 3d4902c4-2028-4f86-b1ca-6d9e76f29d29

	measure 'ADR Vergleich Bezugsjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Ø ADR], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j, m)
		formatString: #,0.00
		lineageTag: 8af1edd3-d368-4eb7-acd3-985d37b55da3

	measure 'ADR Vergleich Vorjahr' =
			VAR j = [Bezugsjahr]
			VAR mb = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j)
			VAR mv = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[month]), REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1)
			VAR m = INTERSECT(mb, mv)
			RETURN CALCULATE([Ø ADR], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = j - 1, m)
		formatString: #,0.00
		lineageTag: a83e0081-7500-450c-9629-1f59e7e2b4d3

	measure 'ADR Veränderung' =
			VAR a = [ADR Vergleich Bezugsjahr]
			VAR v = [ADR Vergleich Vorjahr]
			VAR d = DIVIDE(a - v, v)
			RETURN IF(ISBLANK(v), "kein Vorjahr im Datensatz",
			    IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zu " & [Vergleichszeitraum])
		lineageTag: 02402ea9-d8bc-4991-a4da-7f89199c4a5c

	measure 'ADR Farbe' = IF(ISBLANK([ADR Vergleich Vorjahr]) || [ADR Vergleich Bezugsjahr] >= [ADR Vergleich Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: 931578c8-b5ba-4fd7-a5b1-ff99a370fa55

	measure 'ADR Titel' = "Ø ADR " & FORMAT([Bezugsjahr], "0")
		lineageTag: a63a002c-7443-4c14-b50a-10a5d40e7216

	measure 'ADR Aktuell' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y = j, CALCULATE([Ø ADR], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: #,0.00
		lineageTag: 570b5669-a71d-45e8-8131-6f976adeb061

	measure 'ADR Vorjahre' =
			VAR j = [Bezugsjahr]
			VAR y = MAX(Jahre[Jahr])
			RETURN IF(y <> j, CALCULATE([Ø ADR], REMOVEFILTERS(DIM_DATE), DIM_DATE[year] = y))
		formatString: #,0.00
		lineageTag: 2ab68802-9ba3-4964-ad5a-d3ebbfe0df8d

	measure 'Letzter Monat Datum' = MAXX(CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[Monat]), ALLSELECTED()), DIM_DATE[Monat])
		formatString: MMMM yyyy
		lineageTag: ba6baf58-0afd-432c-b92a-5f6935c43ac4

	measure 'Erster Monat Datum' = MINX(CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[Monat]), ALLSELECTED()), DIM_DATE[Monat])
		formatString: MMMM yyyy
		lineageTag: a34080ac-b049-4df9-af70-11c419587c4a

	measure 'Letzter Monat' = IF(MAX(DIM_DATE[Monat]) = [Letzter Monat Datum], [Umsatz])
		formatString: #,0
		lineageTag: 7db5f381-fe93-488a-be66-19c0fe28f215

	measure Saisonpunkte =
			VAR y = MAX(DIM_DATE[year])
			VAR cur = [Umsatz]
			VAR mx = MAXX(CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[Monat]), ALLSELECTED(), DIM_DATE[year] = y), [Umsatz])
			RETURN IF(cur = mx && MAX(DIM_DATE[Monat]) < [Letzter Monat Datum], cur)
		formatString: #,0
		lineageTag: b96b59ec-f710-4252-a6be-744c2ec7b5d8

	measure Zeitraum =
			VAR t = CALCULATETABLE(SUMMARIZE(FACT_BOOKINGS, DIM_DATE[year]), ALLSELECTED())
			VAR mn = MINX(t, DIM_DATE[year])
			VAR mx = MAXX(t, DIM_DATE[year])
			RETURN IF(mn = mx, FORMAT(mn, "0"), FORMAT(mn, "0") & "–" & FORMAT(mx, "0"))
		lineageTag: 5ec2fc64-bfa9-428e-9bf4-e9f32449a1ab

	measure Hotelauswahl = IF(HASONEVALUE(DIM_HOTEL[hotel]), MAX(DIM_HOTEL[hotel]), "beide Hotels")
		lineageTag: cf6ca359-0c7e-4bd2-80e6-f6cbc1a6bceb

	measure 'Untertitel Segment' = "Umsatz in Euro je Marktsegment, " & [Zeitraum] & ", " & [Hotelauswahl]
		lineageTag: 04e0f7c5-71d4-47ca-b1d6-7958517cbb4d

	measure 'Untertitel Vorlaufzeit' = "Stornoquote in % je Vorlaufzeit-Klasse, " & [Zeitraum] & ", " & [Hotelauswahl]
		lineageTag: 4d7af36d-9575-445a-aa4f-afc620440d56

	measure 'Untertitel Länder' = "Umsatz in Euro je Herkunftsland, die zwölf größten von 178, " & [Zeitraum] & ", " & [Hotelauswahl]
		lineageTag: 9ba95ce4-9ee0-42e0-8e0d-8b8d6042515f

	measure 'Untertitel Monate' = "Umsatz je Anreisemonat in Euro, " & FORMAT([Erster Monat Datum], "MMMM yyyy") & " bis " & FORMAT([Letzter Monat Datum], "MMMM yyyy") & ", " & [Hotelauswahl]
		lineageTag: 33798cc3-ff22-4c7d-889b-d5824e3d7ea6

	column booking_id
		dataType: int64
		formatString: 0
		lineageTag: c8a0be68-3f4d-53fe-ada8-f8ae1e9a4a66
		summarizeBy: none
		sourceColumn: booking_id

		annotation SummarizationSetBy = User

	column hotel_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0f495f0b-a4fb-59b9-870f-835e17374a1f
		summarizeBy: none
		sourceColumn: hotel_id

		annotation SummarizationSetBy = User

	column arrival_date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee75ce7a-1eb3-52f8-901b-8c74bf8c2fa7
		summarizeBy: none
		sourceColumn: arrival_date_key

		annotation SummarizationSetBy = User

	column reservation_status_date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2e9ad294-d081-5d3e-b9bc-bbec11ce897b
		summarizeBy: none
		sourceColumn: reservation_status_date_key

		annotation SummarizationSetBy = User

	column market_segment_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aa4451d2-33e3-5d3e-87ab-7ebf8d51657d
		summarizeBy: none
		sourceColumn: market_segment_id

		annotation SummarizationSetBy = User

	column distribution_channel_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 36bbf7da-4713-5fdc-b071-de11ce4308a0
		summarizeBy: none
		sourceColumn: distribution_channel_id

		annotation SummarizationSetBy = User

	column customer_type_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b8d8f289-0cb3-5c7f-80b9-2febecfa72e9
		summarizeBy: none
		sourceColumn: customer_type_id

		annotation SummarizationSetBy = User

	column meal_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0db363b8-0ac0-5012-a065-004a0004a3a7
		summarizeBy: none
		sourceColumn: meal_id

		annotation SummarizationSetBy = User

	column deposit_type_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5c9fc45e-1193-5375-8a14-891162835e60
		summarizeBy: none
		sourceColumn: deposit_type_id

		annotation SummarizationSetBy = User

	column country_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 23fe0eee-1ec1-533e-947c-4f5465e71db5
		summarizeBy: none
		sourceColumn: country_id

		annotation SummarizationSetBy = User

	column is_canceled
		dataType: int64
		formatString: 0
		lineageTag: bd64ecd0-b736-5676-a364-2041b43a8997
		summarizeBy: none
		sourceColumn: is_canceled

		annotation SummarizationSetBy = User

	column lead_time
		dataType: int64
		formatString: 0
		lineageTag: aa882025-40ab-5f88-b8e8-add441049e38
		summarizeBy: none
		sourceColumn: lead_time

		annotation SummarizationSetBy = User

	column stays_in_weekend_nights
		dataType: int64
		formatString: 0
		lineageTag: 83099bdb-424b-5e03-b456-fe984aa0d05e
		summarizeBy: none
		sourceColumn: stays_in_weekend_nights

		annotation SummarizationSetBy = User

	column stays_in_week_nights
		dataType: int64
		formatString: 0
		lineageTag: 2504574c-bd12-522a-a3c3-e5c8a13dfd6d
		summarizeBy: none
		sourceColumn: stays_in_week_nights

		annotation SummarizationSetBy = User

	column total_nights
		dataType: int64
		formatString: 0
		lineageTag: d91d6a89-2ddd-5264-9af3-64dd222d4481
		summarizeBy: none
		sourceColumn: total_nights

		annotation SummarizationSetBy = User

	column adults
		dataType: int64
		formatString: 0
		lineageTag: b4d30208-7cba-5a43-9a93-40316f47feda
		summarizeBy: none
		sourceColumn: adults

		annotation SummarizationSetBy = User

	column children
		dataType: double
		formatString: 0.0
		lineageTag: 558e495a-3791-59b4-b10d-a27923c25537
		summarizeBy: none
		sourceColumn: children

		annotation SummarizationSetBy = User

	column babies
		dataType: int64
		formatString: 0
		lineageTag: 61896cf8-d934-5d78-886f-eb300e9ad786
		summarizeBy: none
		sourceColumn: babies

		annotation SummarizationSetBy = User

	column total_guests
		dataType: double
		formatString: 0.0
		lineageTag: f3befd67-0d8e-52bb-99c6-48cfbf484c79
		summarizeBy: none
		sourceColumn: total_guests

		annotation SummarizationSetBy = User

	column is_repeated_guest
		dataType: int64
		formatString: 0
		lineageTag: 253e171f-d7a3-50df-8124-a54e7ccf5407
		summarizeBy: none
		sourceColumn: is_repeated_guest

		annotation SummarizationSetBy = User

	column previous_cancellations
		dataType: int64
		formatString: 0
		lineageTag: 72977504-ad85-540a-a6a4-8392495c01d7
		summarizeBy: none
		sourceColumn: previous_cancellations

		annotation SummarizationSetBy = User

	column previous_bookings_not_canceled
		dataType: int64
		formatString: 0
		lineageTag: 1a18feb9-485e-5acc-bf3a-27761abb82e6
		summarizeBy: none
		sourceColumn: previous_bookings_not_canceled

		annotation SummarizationSetBy = User

	column reserved_room_type
		dataType: string
		lineageTag: 7e39ea05-9cca-5a6e-a507-55ccea5ff116
		summarizeBy: none
		sourceColumn: reserved_room_type

		annotation SummarizationSetBy = User

	column assigned_room_type
		dataType: string
		lineageTag: 3d90243d-8415-5e8b-b1c7-26151bafbadf
		summarizeBy: none
		sourceColumn: assigned_room_type

		annotation SummarizationSetBy = User

	column booking_changes
		dataType: int64
		formatString: 0
		lineageTag: 9a4c63eb-f5eb-59fa-a9e3-5324d4761776
		summarizeBy: none
		sourceColumn: booking_changes

		annotation SummarizationSetBy = User

	column days_in_waiting_list
		dataType: int64
		formatString: 0
		lineageTag: ab0e09ad-ada5-59c9-b051-0748eee6350f
		summarizeBy: none
		sourceColumn: days_in_waiting_list

		annotation SummarizationSetBy = User

	column adr
		dataType: double
		formatString: #,0.00
		lineageTag: 7ab7ac27-a6d4-59db-9d56-124c2f9e4341
		summarizeBy: none
		sourceColumn: adr

		annotation SummarizationSetBy = User

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 6591d06c-1969-5a01-8f46-e9467af5c094
		summarizeBy: none
		sourceColumn: revenue

		annotation SummarizationSetBy = User

	column required_car_parking_spaces
		dataType: int64
		formatString: 0
		lineageTag: 314b5cd9-ce97-5831-9677-1be635f3ed0c
		summarizeBy: none
		sourceColumn: required_car_parking_spaces

		annotation SummarizationSetBy = User

	column total_of_special_requests
		dataType: int64
		formatString: 0
		lineageTag: 95593c02-2645-5454-8498-090f2d50fbbb
		summarizeBy: none
		sourceColumn: total_of_special_requests

		annotation SummarizationSetBy = User

	column reservation_status
		dataType: string
		lineageTag: e81cc3ff-6de1-5f29-8591-1ab1dc8131cb
		summarizeBy: none
		sourceColumn: reservation_status

		annotation SummarizationSetBy = User

	column Lead-Time-Bucket =
			SWITCH(TRUE(),
			    FACT_BOOKINGS[lead_time] <= 7, "0–7 Tage",
			    FACT_BOOKINGS[lead_time] <= 30, "8–30 Tage",
			    FACT_BOOKINGS[lead_time] <= 90, "31–90 Tage",
			    "über 90 Tage")
		dataType: string
		lineageTag: b49af994-78fc-51ff-93a3-f1b0e94a7ad5
		summarizeBy: none
		sortByColumn: Lead-Time-Sortierung

		annotation SummarizationSetBy = User

	column Lead-Time-Sortierung =
			SWITCH(TRUE(),
			    FACT_BOOKINGS[lead_time] <= 7, 1,
			    FACT_BOOKINGS[lead_time] <= 30, 2,
			    FACT_BOOKINGS[lead_time] <= 90, 3,
			    4)
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 20b7107d-d08c-54ff-865f-8a129e4e95cb
		summarizeBy: none

		annotation SummarizationSetBy = User

	partition FACT_BOOKINGS = m
		mode: import
		source =
				let
				    Quelle = PostgreSQL.Database("supabase.butscher.cloud:5433", "hotel"),
				    Tabelle = Quelle{[Schema="hotel_bi",Item="fact_bookings"]}[Data],
				    Typen = Table.TransformColumnTypes(Tabelle, {{"is_canceled", Int64.Type}, {"is_repeated_guest", Int64.Type}})
				in
				    Typen

	annotation PBI_ResultType = Table

